# Plan Approval Workflow
# Integrates validation into plan approval process
# Author: RALF-Executor (TASK-1769913001)
# Created: 2026-02-01

workflow:
  name: "Plan Approval with Validation"
  version: "1.0"

# Workflow stages
stages:
  - name: "validate"
    description: "Validate plan before approval"
    required: true
    validator:
      script: "lib/plan_validator.py"
      args:
        - "--project-root"
        - "{project_root}"
        - "{plan_path}"
      on_failure:
        action: "block"
        message: "Plan validation failed. Please fix errors before approval."
      on_warning:
        action: "warn"
        message: "Plan validation warnings detected. Review before proceeding."

  - name: "approve"
    description: "Manual approval after validation"
    required: true
    depends_on: ["validate"]
    condition:
      - validation_passed: true

  - name: "ready_to_start"
    description: "Mark plan as ready to start"
    required: true
    depends_on: ["approve"]
    updates:
      - path: "6-roadmap/STATE.yaml"
        field: "plans.ready_to_start"
        action: "add"
        value: "{plan_id}"

# Validation rules
validation_rules:
  critical:
    - name: "file_existence"
      description: "All referenced files must exist"
      severity: "error"
      check: "files_exist"

    - name: "no_self_dependency"
      description: "Plan cannot depend on itself"
      severity: "error"
      check: "no_circular_deps"

  warnings:
    - name: "staleness"
      description: "Warn if plan is > 30 days old"
      severity: "warning"
      threshold_days: 30

    - name: "stale_problem"
      description: "Warn if problem statement appears resolved"
      severity: "warning"
      check: "problem_keywords"

# Integration points
integration:
  planner:
    before_queue: true
    before_ready_to_start: true

  executor:
    before_execution: true
    on_invalid_plan:
      action: "skip"
      notify: "planner"

# Exit codes
exit_codes:
  success: 0
  validation_failed: 1
  plan_not_found: 2
  state_not_found: 3
