# Task Completion Workflow
# Triggers automatic roadmap state synchronization upon task completion

name: task-completion
version: "1.0.0"
description: |
  Workflow that executes when a task is completed. Automatically synchronizes
  the roadmap STATE.yaml to prevent drift between documented state and actual state.

triggers:
  - event: task.completed
  - event: task.partial
  - event: task.failed
  - manual: true

steps:
  # Step 1: Validate task completion
  - id: validate
    name: Validate Task Completion
    action: validate_completion
    inputs:
      task_id: "{{ event.task_id }}"
      task_file: "{{ event.task_file }}"
      result: "{{ event.result }}"
    outputs:
      valid: boolean
      task_data: object

  # Step 2: Update roadmap state
  - id: sync_state
    name: Sync Roadmap State
    action: execute_script
    condition: "{{ steps.validate.outputs.valid }}"
    inputs:
      script: |
        python3 << 'PYTHON_SCRIPT'
        import sys
        sys.path.insert(0, "{{ env.RALF_ENGINE_DIR }}/lib")
        from roadmap_sync import RoadmapSync

        sync = RoadmapSync("{{ env.RALF_PROJECT_DIR }}/STATE.yaml")
        result = sync.sync_task_completion(
            task_id="{{ event.task_id }}",
            task_result="{{ event.result }}",
            auto_save=True
        )

        print(f"SYNC_RESULT: {'SUCCESS' if result.success else 'FAILED'}")
        print(f"CHANGES_MADE: {len(result.changes_made)}")
        for change in result.changes_made:
            print(f"  - {change}")

        if result.errors:
            print(f"ERRORS: {len(result.errors)}")
            for error in result.errors:
                print(f"  - {error}")

        sys.exit(0 if result.success else 1)
        PYTHON_SCRIPT
    outputs:
      sync_success: boolean
      changes: list

  # Step 3: Update events log
  - id: log_event
    name: Log Sync Event
    action: append_yaml
    inputs:
      file: "{{ env.RALF_PROJECT_DIR }}/.autonomous/communications/events.yaml"
      data:
        timestamp: "{{ now }}"
        type: roadmap_sync
        task_id: "{{ event.task_id }}"
        result: "{{ event.result }}"
        sync_success: "{{ steps.sync_state.outputs.sync_success }}"
        changes_made: "{{ steps.sync_state.outputs.changes }}"

  # Step 4: Handle sync failures
  - id: handle_failure
    name: Handle Sync Failure
    action: notify
    condition: "{{ not steps.sync_state.outputs.sync_success }}"
    inputs:
      channel: planner
      message: |
        Roadmap sync failed for task {{ event.task_id }}
        Manual STATE.yaml update may be required.

outputs:
  success: "{{ steps.sync_state.outputs.sync_success }}"
  changes: "{{ steps.sync_state.outputs.changes }}"

rollback:
  # If sync fails, manual intervention is required
  action: notify_planner
  message: |
    Task completion workflow failed for {{ event.task_id }}.
    Please manually verify STATE.yaml is consistent.

---
# Alternative: Simple bash-based sync (fallback)
# This can be used if the Python library is not available

fallback_sync:
  description: "Bash-based state synchronization (fallback)"
  script: |
    #!/bin/bash
    set -e

    STATE_FILE="${RALF_PROJECT_DIR}/STATE.yaml"
    TASK_ID="${1:-unknown}"
    RESULT="${2:-success}"

    if [[ ! -f "$STATE_FILE" ]]; then
        echo "ERROR: STATE.yaml not found"
        exit 1
    fi

    # Update timestamp
    sed -i.bak "s/last_updated:.*/last_updated: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"/" "$STATE_FILE"
    rm -f "${STATE_FILE}.bak"

    echo "Updated STATE.yaml timestamp"

    # Note: Full plan status updates require Python library
    echo "For full sync, ensure roadmap_sync.py is available"
