# RALF Configuration
# ==================
#
# This is the default configuration file for RALF (Recursive Autonomous Learning Framework).
#
# Configuration File Location:
#   - User config: ~/.blackbox5/config.yaml (overrides defaults)
#   - Default config: 2-engine/.autonomous/config/default.yaml (this file)
#
# How to Customize:
#   1. Copy this file to ~/.blackbox5/config.yaml
#   2. Modify the values you want to change
#   3. RALF will use your values, falling back to defaults for missing settings
#
# Configuration Hierarchy:
#   User config (~/.blackbox5/config.yaml) > Default config (this file) > Built-in defaults
#
# Version: 1.0.0
#   - Increment this field when breaking changes are introduced to config schema

version: "1.0"

# ============================================================================
# Thresholds
# ============================================================================
# Control when RALF takes certain actions (e.g., invoke skills, add tasks to queue)

thresholds:
  # Skill Invocation Confidence Threshold (0-100)
  #   - Purpose: Minimum confidence score required to invoke a BMAD skill
  #   - Range: 0 (always invoke) to 100 (never invoke)
  #   - Default: 70 (balanced - invoke skills when confidence is high)
  #   - Impact:
  #       * Lower value = More aggressive skill invocation (may invoke inappropriate skills)
  #       * Higher value = More conservative skill invocation (may miss useful skills)
  #   - Example:
  #       * 60: More aggressive (good for exploration, may have false positives)
  #       * 70: Balanced (default, recommended for most users)
  #       * 80: Conservative (only invoke skills when very confident)
  skill_invocation_confidence: 70

  # Queue Depth Target Minimum (0-10)
  #   - Purpose: Minimum number of tasks to keep in the queue
  #   - Range: 0 (no minimum) to 10 (keep at least 10 tasks)
  #   - Default: 3 (maintain healthy queue depth)
  #   - Impact:
  #       * Lower value = Less queue maintenance (may run out of tasks)
  #       * Higher value = More proactive task generation (queue always stocked)
  #   - Note: Should be <= queue_depth_max
  queue_depth_min: 3

  # Queue Depth Target Maximum (0-20)
  #   - Purpose: Maximum number of tasks to keep in the queue
  #   - Range: 0 (no limit) to 20 (cap at 20 tasks)
  #   - Default: 5 (prevent queue overflow)
  #   - Impact:
  #       * Lower value = Smaller queue (focus on current work, less planning ahead)
  #       * Higher value = Larger queue (more planning ahead, may include lower-priority work)
  #   - Note: Should be >= queue_depth_min
  queue_depth_max: 5

  # Loop Timeout Seconds (30-600)
  #   - Purpose: Seconds before an agent is considered inactive/unresponsive
  #   - Range: 30 (30 seconds) to 600 (10 minutes)
  #   - Default: 120 (2 minutes)
  #   - Impact:
  #       * Lower value = Faster timeout detection (may falsely flag slow agents as dead)
  #       * Higher value = Slower timeout detection (may take longer to detect dead agents)
  #   - Example:
  #       * 60: Quick timeout (good for fast loops, may have false positives)
  #       * 120: Balanced (default, recommended for most users)
  #       * 300: Slow timeout (good for long-running tasks, slower detection)
  loop_timeout_seconds: 120

# ============================================================================
# Routing
# ============================================================================
# Control how tasks are routed to agents

routing:
  # Default Agent
  #   - Purpose: Default agent to handle tasks when no specific routing rule matches
  #   - Valid values: "executor", "planner", "analyst"
  #   - Default: "executor" (most tasks are execution tasks)
  #   - Impact: Determines which agent handles tasks by default
  default_agent: "executor"

  # Task Type Routing
  #   - Purpose: Route specific task types to specific agents
  #   - Format: Map of task type -> agent name
  #   - Example: "feature" tasks go to "executor", "research" tasks go to "analyst"
  #   - Impact: Overrides default_agent for matching task types
  task_type_routing:
    # Task type -> Agent mappings
    feature: "executor"      # Feature implementation tasks
    fix: "executor"          # Bug fix tasks
    research: "executor"     # Research tasks (can be changed to "analyst" if analyst agent exists)
    refactor: "executor"     # Refactoring tasks
    analyze: "executor"      # Analysis tasks (can be changed to "analyst" if analyst agent exists)
    organize: "executor"     # Organization tasks
    improve: "executor"      # Improvement tasks

# ============================================================================
# Notifications
# ============================================================================
# Control when and how RALF sends notifications

notifications:
  # Enable Notifications
  #   - Purpose: Master switch for notifications
  #   - Valid values: true (enabled), false (disabled)
  #   - Default: false (notifications disabled by default)
  #   - Impact: When false, no notifications are sent regardless of other settings
  enabled: false

  # Notify on Task Completion
  #   - Purpose: Send notification when a task is completed
  #   - Valid values: true, false
  #   - Default: false
  #   - Impact: Controls completion notifications (if enabled above)
  on_task_completion: false

  # Notify on Error
  #   - Purpose: Send notification when an error occurs
  #   - Valid values: true, false
  #   - Default: true (errors are important)
  #   - Impact: Controls error notifications (if enabled above)
  on_error: true

  # Notify on Milestone
  #   - Purpose: Send notification when a milestone is reached
  #   - Valid values: true, false
  #   - Default: false
  #   - Impact: Controls milestone notifications (if enabled above)
  #   - Milestones: Feature completion, health threshold reached, etc.
  on_milestone: false

# ============================================================================
# Advanced Settings (Optional)
# ============================================================================
# Advanced configuration options for power users

# Advanced settings are commented out by default.
# Uncomment and modify if you need these features.

# advanced:
#   # Per-Agent Configuration
#   #   - Purpose: Override settings for specific agents
#   #   - Example: Different skill thresholds for executor vs planner
#   # per_agent_config:
#     # executor:
#     #   thresholds:
#     #     skill_invocation_confidence: 70
#     # planner:
#     #   thresholds:
#     #     skill_invocation_confidence: 80

#   # Configuration Reload Trigger
#   #   - Purpose: How config reload is triggered
#   #   - Valid values: "signal" (SIGUSR1), "manual" (explicit command)
#   #   - Default: "manual" (safer, explicit control)
#   # config_reload_trigger: "manual"

# ============================================================================
# Notes
# ============================================================================
#
# Configuration Best Practices:
#   1. Start with defaults, then adjust based on your needs
#   2. Lower thresholds gradually (don't go to extremes immediately)
#   3. Monitor system behavior after changing configuration
#   4. Document your custom configuration choices for your team
#
# Troubleshooting:
#   - If RALF is not using your config: Check file path (~/.blackbox5/config.yaml)
#   - If config validation fails: Check value ranges (e.g., confidence must be 0-100)
#   - If RALF crashes on startup: Delete config file, defaults will be used
#
# Support:
#   - Documentation: operations/.docs/configuration-guide.md
#   - Issues: Check logs for configuration errors
#
# ============================================================================
# End of Configuration File
# ============================================================================
