# RALF Production Environment Configuration
# ==========================================
# Production environment configuration.

version: "2.0.0"

system:
  environment: "production"
  log_level: "WARNING"
  debug_mode: false

api:
  host: "ralf.example.com"
  port: 443
  timeout: 60
  cors_enabled: false
  ssl_required: true
  rate_limit:
    enabled: true
    requests_per_minute: 1000

database:
  host: "prod-db.ralf.example.com"
  port: 5432
  name: "ralf_prod"
  ssl_mode: "require"
  pool_size: 50
  timeout: 30

security:
  api_key_required: true
  rate_limiting: true
  encryption:
    algorithm: "AES-256-GCM"
    key_iterations: 100000

features:
  # Stable features only
  automated_testing: true
  github_integration: true
  api_gateway: true
  code_review: false
  performance_monitoring: true

execution:
  max_concurrent_tasks: 10
  task_timeout: 3600
  retry_attempts: 3
  retry_delay: 60
  verbose_logging: false

monitoring:
  enabled: true
  metrics_port: 9090
  alerting:
    enabled: true
    webhook_url: "${ALERT_WEBHOOK_URL}"  # From environment variable

# Production-specific settings
production:
  auto_scaling: true
  backup_enabled: true
  audit_logging: true
  high_availability: true

# Backup and recovery
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM UTC
  retention_days: 30
  storage: "s3://ralf-backups"
