# Task Execution Workflow
# Defines the mandatory pre-execution research and execution phases

name: task-execution
version: "2.0.0"
description: |
  Standard workflow for executing tasks with mandatory pre-execution research.
  Research is not optional - it prevents duplicate work and validates assumptions.

triggers:
  - event: task.claimed
  - manual: true

phases:
  # Phase 1: Pre-Execution Research (MANDATORY)
  - id: research
    name: Pre-Execution Research
    required: true
    description: |
      Research MUST be completed before any code changes. This phase prevents
      duplicate work and ensures integration with existing code.

    steps:
      - id: check_duplicates
        name: Check for Duplicate Tasks
        required: true
        action: search_and_verify
        inputs:
          search_paths:
            - "{{ env.RALF_PROJECT_DIR }}/.autonomous/tasks/completed/"
            - "{{ env.RALF_PROJECT_DIR }}/tasks/completed/"
          search_terms: "{{ task.keywords }}"
          check_commits: true
          commit_since: "2 weeks ago"
        outputs:
          duplicates_found: boolean
          similar_tasks: list
          recent_commits: list

      - id: gather_context
        name: Gather Context
        required: true
        action: read_and_analyze
        inputs:
          task_file: "{{ event.task_file }}"
          target_files: "{{ task.files_to_modify }}"
          related_docs: "{{ task.related_documentation }}"
        outputs:
          files_exist: boolean
          context_summary: string
          dependencies: list
          integration_risks: list

      - id: document_research
        name: Document Research Findings
        required: true
        action: write_markdown
        inputs:
          target: "{{ env.RALF_RUN_DIR }}/THOUGHTS.md"
          section: "Pre-Execution Research"
          template: |
            ## Pre-Execution Research

            ### Duplicate Check
            - [ ] Checked completed/ for similar tasks: {{ steps.check_duplicates.outputs.duplicates_found }}
            - [ ] Checked recent commits: {{ steps.check_duplicates.outputs.recent_commits | length }} commits
            - Result: {{ steps.check_duplicates.outputs.duplicates_found | ternary("Potential duplicate found", "No duplicates found") }}
            {{#if steps.check_duplicates.outputs.similar_tasks }}
            Similar tasks found:
            {{#each steps.check_duplicates.outputs.similar_tasks }}
            - {{ this }}
            {{/each}}
            {{/if}}

            ### Context Gathered
            - Files read: {{ steps.gather_context.outputs.context_summary }}
            - Target files exist: {{ steps.gather_context.outputs.files_exist }}
            - Dependencies identified: {{ steps.gather_context.outputs.dependencies | join(", ") }}

            ### Risk Assessment
            - Integration risks: {{ steps.gather_context.outputs.integration_risks | length > 0 | ternary("medium/high", "low") }}
            {{#if steps.gather_context.outputs.integration_risks }}
            Risks:
            {{#each steps.gather_context.outputs.integration_risks }}
            - {{ this }}
            {{/each}}
            {{/if}}
            - Blockers: [Document any blockers found]

      - id: research_validation
        name: Validate Research Completion
        required: true
        action: validate_checklist
        inputs:
          checks:
            - "Duplicate check completed"
            - "Context gathered"
            "Research documented in THOUGHTS.md"
            - "No blockers or blockers documented"
        condition: "{{ not steps.check_duplicates.outputs.duplicates_found or task.force_execution }}"
        on_failure:
          action: block_execution
          message: |
            Research phase incomplete or duplicates found.
            Review THOUGHTS.md and resolve before proceeding.

  # Phase 2: Task Execution
  - id: execution
    name: Task Execution
    required: true
    depends_on: research
    description: |
      Execute the task after research is complete.

    steps:
      - id: claim_task
        name: Claim Task
        action: log_event
        inputs:
          file: "{{ env.RALF_PROJECT_DIR }}/.autonomous/communications/events.yaml"
          event:
            timestamp: "{{ now }}"
            task_id: "{{ event.task_id }}"
            type: started
            agent: executor

      - id: execute_task
        name: Execute Task
        action: execute_task_logic
        inputs:
          task_file: "{{ event.task_file }}"
          approach: "{{ task.approach }}"
        outputs:
          files_modified: list
          success: boolean

      - id: validate_execution
        name: Validate Execution
        action: validate_checklist
        inputs:
          checks:
            - "Code imports/validates successfully"
            - "Integration with existing system verified"
            - "No breaking changes introduced"
            - "Tests pass (if applicable)"

  # Phase 3: Documentation and Completion
  - id: completion
    name: Documentation and Completion
    required: true
    depends_on: execution

    steps:
      - id: create_docs
        name: Create Required Documentation
        action: generate_docs
        inputs:
          run_dir: "{{ env.RALF_RUN_DIR }}"
          required_files:
            - THOUGHTS.md
            - RESULTS.md
            - DECISIONS.md
          templates:
            THOUGHTS.md: "{{ env.RALF_ENGINE_DIR }}/templates/THOUGHTS.md.template"
            RESULTS.md: "{{ env.RALF_ENGINE_DIR }}/templates/RESULTS.md.template"
            DECISIONS.md: "{{ env.RALF_ENGINE_DIR }}/templates/DECISIONS.md.template"

      - id: move_task
        name: Move Task to Completed
        action: move_file
        inputs:
          source: "{{ env.RALF_PROJECT_DIR }}/.autonomous/tasks/active/{{ event.task_file }}"
          destination: "{{ env.RALF_PROJECT_DIR }}/.autonomous/tasks/completed/{{ event.task_file }}"

      - id: commit_changes
        name: Commit Changes
        action: git_commit
        inputs:
          message: |
            executor: [{{ now | format("YYYYMMDD-HHmmss") }}] {{ event.task_id }} - {{ task.title }}

            - {{ steps.execute_task.outputs.files_modified | length }} files modified
            - Task: {{ event.task_id }}
            - Validation: passed

            Co-authored-by: Claude <claude@blackbox5.local>

      - id: log_completion
        name: Log Completion
        action: log_event
        inputs:
          file: "{{ env.RALF_PROJECT_DIR }}/.autonomous/communications/events.yaml"
          event:
            timestamp: "{{ now }}"
            task_id: "{{ event.task_id }}"
            type: completed
            result: "{{ steps.execute_task.outputs.success | ternary('success', 'failed') }}"
            commit_hash: "{{ steps.commit_changes.outputs.commit_hash }}"

outputs:
  success: "{{ steps.execute_task.outputs.success }}"
  files_modified: "{{ steps.execute_task.outputs.files_modified }}"
  research_completed: "{{ steps.research_validation.outputs.valid }}"

rollback:
  # If execution fails, task stays in active/
  action: notify_planner
  message: |
    Task execution failed for {{ event.task_id }}.
    Task remains in active/ for retry or reassignment.

---
# Research Phase Validation Rules

validation_rules:
  research_required:
    description: "Research phase cannot be skipped"
    check: "phases.research.completed == true"
    severity: error
    message: "Pre-execution research is mandatory. Complete research phase before execution."

  duplicates_checked:
    description: "Duplicate check must be performed"
    check: "steps.check_duplicates.outputs != null"
    severity: error
    message: "Duplicate detection not performed. Run duplicate check before proceeding."

  context_gathered:
    description: "Context must be gathered"
    check: "steps.gather_context.outputs.files_exist != null"
    severity: error
    message: "Context gathering incomplete. Read all target files before modifying."

  research_documented:
    description: "Research must be documented"
    check: "file_exists('{{ env.RALF_RUN_DIR }}/THOUGHTS.md') and contains('## Pre-Execution Research')"
    severity: error
    message: "Research findings not documented. Add research section to THOUGHTS.md."

---
# Research Checklist Template

research_checklist:
  duplicate_detection:
    - Check completed/ for similar tasks
    - Check recent commits for related work
    - Verify no duplicate work in progress
    - Document findings in THOUGHTS.md

  context_gathering:
    - Read task file completely
    - Read all target files before modifying
    - Check related documentation
    - Identify dependencies
    - Assess integration risks

  documentation:
    - Document duplicate check results
    - List files read
    - Note key findings
    - Identify blockers or unknowns
    - Complete risk assessment

---
# Execution Gate

execution_gate:
  description: "Gate that prevents execution without research"
  condition: "phases.research.status == 'completed'"
  on_block:
    action: log_event
    inputs:
      file: "{{ env.RALF_PROJECT_DIR }}/.autonomous/communications/events.yaml"
      event:
        timestamp: "{{ now }}"
        task_id: "{{ event.task_id }}"
        type: blocked
        reason: "Research phase not completed"
        message: "Execution blocked: Pre-execution research is mandatory"
